import {
  gray,
  blue,
  green,
  yellow,
  orange,
  red,
  purple,
  pink,
  lightblue,
  cyan,
  magenta,
} from "waver-color";

export const colors = {
  black: "#111",
  white: "#fff",
  gray: gray.colors,
  blue: blue.colors,
  green: green.colors,
  yellow: yellow.colors,
  orange: orange.colors,
  red: red.colors,
  purple: purple.colors,
  pink: pink.colors,
};

export const WaverThemes = {
  primary: [lightblue.get("6d"), lightblue.get("7d")],
  foreground: ["#ccd6dbee", "#35393b"],
  activeForeground: ["#aab8bf", "#464c4f"],
  secondaryForeground: ["#d5dbde90", "#35393b90"],
  ignored: ["#d5dbde50", "#35393b50"],
  faded: ["#d5dbde10", "#35393b10"],
  border: ["#141414", "#ebebeb"],
  background: ["#0f0f0f", "#ffffff"],
  activeBackground: ["#161616", "#f7f7f7"],
  selectionBackground: ["#eeeeee24", "#22222224"],
  selectionBackgroundActive: ["#eeeeee24", "#22222224"],
  selectionBackgroundInactive: ["#eeeeee16", "#22222216"],
  comment: ["#768085dd", "#a1a9ad"],
  string: [gray.get("3d"), gray.get("7d")],
  variable: [pink.get("6d"), pink.get("7d")],
  keyword: [lightblue.get("6d"), lightblue.get("7d")],
  number: [green.get("6dd"), green.get("7dd")],
  boolean: [green.get("6dd"), green.get("7dd")],
  operator: [yellow.get("6dd"), yellow.get("7dd")],
  function: [yellow.get("6dd"), yellow.get("7dd")],
  constant: [green.get("6dd"), green.get("7dd")],
  class: [cyan.get("6dd"), cyan.get("7dd")],
  interface: [cyan.get("6dd"), cyan.get("7dd")],
  type: [cyan.get("6dd"), cyan.get("7dd")],
  builtin: [green.get("6dd"), green.get("7dd")],
  property: [lightblue.get("6d"), lightblue.get("7d")],
  namespace: [lightblue.get("6d"), lightblue.get("7d")],
  punctuation: [gray.get("3d"), gray.get("7d")],
  decorator: [red.get("6dd"), red.get("7dd")],
  regex: [red.get("6dd"), red.get("7dd")],
  gray: [gray.get("3d"), gray.get("7d")],
  green: [green.get("5d"), green.get("7d")],
  cyan: [cyan.get("5d"), cyan.get("7d")],
  blue: [lightblue.get("5d"), lightblue.get("7d")],
  red: [red.get("5d"), red.get("7d")],
  orange: [orange.get("5d"), orange.get("7d")],
  yellow: [yellow.get("5d"), yellow.get("7d")],
  magenta: [magenta.get("5d"), magenta.get("7d")],
} satisfies Record<string, [string, string] | string>;
